name: Next_CI/CD

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop

jobs:
  run_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # - name: Run lint&prettier
      #   run: npm run fix

      - name: Run lint&prettier
        run: npm run test
